include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
  errors:
    invalid_annotation_target: ignore
    no_leading_underscores_for_local_identifiers: ignore

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true
    sort_child_properties_last: true
    sort_pub_dependencies: true