name: smart_parking
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <=4.0.0'

dependencies:
  chucker_flutter: ^1.6.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  mobile_scanner: ^3.2.0
  pretty_dio_logger: ^1.3.1
  qr_flutter: ^4.0.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  ios: true

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/